export const navBarState = state => state.navBarState
export const breadCurbList = state => state.breadCurbList
export const coverState = state => state.coverState
export const indexListDetail = state => state.indexListDetail
export const fixOneList = state => state.fixOneList
export const fixOneName = state => state.fixOneName
export const groupDelete = state => state.groupDelete
export const loadState = state => state.loadState
export const allListTotal = state => state.allListTotal
